name: calcu_x
description: A simple calculator with health and normal modes.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.1.0

  cupertino_icons: ^1.0.2
